name: github pages

on:
  push:
    branches:
      - master # default branch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: tar -czvf blog-zip.tar ./front-blog 
      - name: Copy blog
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./blog-zip.tar
          remote: /home/blog/blog-zip.tar
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
          script: 
                  tar zxvf  /home/blog/blog-zip.tar &&
                    cd /home/blog/blog && 
                     yarn install  &&
                     yarn build &&
                     yarn start 
                 
