name: github pages

on:
  push:
    branches:
      - master # default branch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: tar -czvf server-zip.tar ./server2 
      - name: Copy  server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./server-zip.tar
          remote: /home/blog/server-zip.tar
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script:  rm -rf /home/blog/server &&
                   tar zxvf /home/blog/server-zip.tar &&
                   mv /home/blog/server2  /home/blog/server &&
                   cd /home/blog/server &&
                   yarn install &&
                   yarn stop &&
                   yarn start
                   
                
