name: github pages

on:
  push:
    branches:
      - master # default branch
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: yarn bootstrap
      - run: tar -czvf ./front-blog ./blog-zip
      - run: tar -czvf ./server2 ./server-zip
      - name: Copy  front-back
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./front-back/dist
          remote: /usr/share/nginx/html/back
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
      - name: Copy blog
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./blog-zip
          remote: /home/blog/blog
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
      - name: Copy  server
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./server-zip
          remote: /home/blog/server
          host: ${{secrets.HOST}}
          username: root
          password: ${{secrets.PASSWORD}}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: 
                  fuser -k -n tcp 7002 &&
                  fuser -k -n tcp 3000 &&
                  tar /home/blog/blog &&
                  tar /home/blog/server && 
                   cd /home/blog/server &&
                   yarn install &&
                   yarn stop &&
                   yarn start &&
                   cd /home/blog/blog && 
                   yarn install  &&
                   yarn build &&
                   yarn start 
